version: '3.4'
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo-data:/data/db

  server:
    build:
      context: ./server
      target: production
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    ports:
      - ${PORT}:${PORT}

  client:
    build:
      context: ./client
      target: production
      args:
        - VUE_APP_API_URL=${VUE_APP_API_URL}
    ports:
      - '${CLIENTPORT}:80'
