version: '3.4'
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo-data:/data/db

  server:
    build:
      context: ./server
      target: development
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    ports:
      - ${PORT}:${PORT}
