version: '3.4'
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo-data:/data/db

  server:
    build:
      context: ./server
      target: development
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    ports:
      - ${PORT}:${PORT}

  client:
    build:
      context: ./client
      target: development
    volumes:
      - ./client:/app
    depends_on:
      - server
    environment:
      - PORT=${CLIENTPORT}
      - VUE_APP_API_URL=${VUE_APP_API_URL}
    ports:
      - '${CLIENTPORT}:${CLIENTPORT}'
